name: internvl
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pip
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - pip:
      - flash-attn==2.3.6
      - timm==0.9.12
      - openmim
      - mmcv-full==1.6.2
      - transformers==4.37.2
      - opencv-python
      - termcolor
      - yacs
      - pyyaml
      - scipy
      - deepspeed==0.13.5
      - pycocoevalcap
      - tqdm
